In [1]:
#import all necessary liberty

%matplotlib inline
#import matplotlib.pyplot as plt
from matplotlib import pyplot as plt
import tensorflow as tf
import numpy as np
from sklearn.metrics import confusion_matrix

import pandas as pd

#missing value handle
from sklearn.preprocessing import Imputer


#from sklearn.preprocessing import Imputer
#import impute.SimpleImputer from sklearn
#import impute.SimpleImputer from sklearn

#To shuffle the data set
from sklearn.utils import shuffle

from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Activation
from keras.layers import Dropout
from keras.optimizers import SGD
from keras.optimizers import Adam
#from sklearn.utils import shuffle
import csv

#spliting dataset into traning set and test set
from sklearn.model_selection import train_test_split
import itertools
import sys

Using TensorFlow backend.

In [2]:
#import csv data_set

df = pd.read_csv('./data-withoutapp.csv',na_values=['NA','?'])
data_frame = pd.read_csv('./data-withoutapp.csv')
#df=data_frame

data_frame.shape

(835, 15)

In [3]:
data_frame.head(3)

,Age,Sex,Smoking,HTN,DLP,DM,Physical Exercise,Family History,Drug History,Psychological Stress,Chest Pain,Dyspnea,Palpitation,ECG,IHD-HeartAttack
0,65,Male,no,yes,no,yes,no,no,yes,no,yes,no,no,abnormal,Yes
1,48,Male,no,yes,no,yes,no,no,yes,no,yes,no,no,abnormal,No
2,80,Male,ex,yes,no,yes,yes,no,yes,no,no,no,no,abnormal,Yes

In [4]:
df.columns

Index(['Age', 'Sex', 'Smoking', 'HTN', 'DLP', 'DM', 'Physical Exercise',
       'Family History', 'Drug History', 'Psychological Stress', 'Chest Pain',
       'Dyspnea', 'Palpitation', 'ECG', 'IHD-HeartAttack'],
      dtype='object')

In [5]:
df.isnull().any()

Age                      True
Sex                      True
Smoking                  True
HTN                      True
DLP                      True
DM                       True
Physical Exercise        True
Family History           True
Drug History             True
Psychological Stress     True
Chest Pain               True
Dyspnea                  True
Palpitation              True
ECG                      True
IHD-HeartAttack         False
dtype: bool

In [6]:
df.isnull().values.any()

True

In [7]:
df.isnull().sum()

Age                      4
Sex                      1
Smoking                  3
HTN                      3
DLP                      8
DM                       1
Physical Exercise        9
Family History           7
Drug History            28
Psychological Stress    15
Chest Pain               3
Dyspnea                  2
Palpitation              5
ECG                     36
IHD-HeartAttack          0
dtype: int64

In [8]:
data_frame.isnull().sum()

Age                     3
Sex                     0
Smoking                 0
HTN                     0
DLP                     0
DM                      0
Physical Exercise       0
Family History          0
Drug History            0
Psychological Stress    0
Chest Pain              0
Dyspnea                 0
Palpitation             0
ECG                     0
IHD-HeartAttack         0
dtype: int64

In [9]:
df.Age.dtype

dtype('float64')

In [10]:
df.Age[0]

65.0

In [11]:
data_frame.Age[0]

'65'

In [12]:
df.Age.shape[0]

835

In [13]:
for i in range(df.Age.shape[0]):
    print(i,df.Age[i])

0 65.0
1 48.0
2 80.0
3 67.0
4 55.0
5 85.0
6 80.0
7 75.0
8 26.0
9 69.0
10 65.0
11 50.0
12 63.0
13 62.0
14 63.0
15 65.0
16 55.0
17 45.0
18 60.0
19 70.0
20 54.0
21 50.0
22 26.0
23 91.0
24 80.0
25 47.0
26 50.0
27 42.0
28 75.0
29 60.0
30 68.0
31 53.0
32 55.0
33 70.0
34 34.0
35 50.0
36 55.0
37 70.0
38 85.0
39 45.0
40 70.0
41 65.0
42 50.0
43 42.0
44 61.0
45 70.0
46 47.0
47 55.0
48 50.0
49 50.0
50 55.0
51 85.0
52 41.0
53 65.0
54 67.0
55 70.0
56 68.0
57 68.0
58 42.0
59 30.0
60 75.0
61 49.0
62 50.0
63 60.0
64 50.0
65 40.0
66 30.0
67 43.0
68 64.0
69 45.0
70 64.0
71 45.0
72 30.0
73 57.0
74 90.0
75 36.0
76 45.0
77 60.0
78 75.0
79 62.0
80 62.0
81 65.0
82 76.0
83 40.0
84 53.0
85 59.0
86 44.0
87 50.0
88 63.0
89 49.0
90 48.0
91 40.0
92 60.0
93 45.0
94 nan
95 88.0
96 65.0
97 67.0
98 55.0
99 50.0
100 54.0
101 52.0
102 60.0
103 50.0
104 65.0
105 55.0
106 58.0
107 60.0
108 60.0
109 45.0
110 50.0
111 94.0
112 45.0
113 54.0
114 40.0
115 58.0
116 69.0
117 75.0
118 52.0
119 65.0
120 89.0
121 47.0
122 55.0
123 60.0
124 40.0
125 36.0
126 75.0
127 55.0
128 60.0
129 59.0
130 63.0
131 55.0
132 65.0
133 54.0
134 52.0
135 60.0
136 75.0
137 55.0
138 55.0
139 59.0
140 55.0
141 40.0
142 45.0
143 67.0
144 57.0
145 75.0
146 42.0
147 66.0
148 56.0
149 56.0
150 63.0
151 60.0
152 38.0
153 84.0
154 65.0
155 55.0
156 65.0
157 35.0
158 67.0
159 55.0
160 57.0
161 58.0
162 85.0
163 60.0
164 30.0
165 35.0
166 69.0
167 87.0
168 65.0
169 50.0
170 53.0
171 65.0
172 43.0
173 48.0
174 58.0
175 30.0
176 52.0
177 55.0
178 65.0
179 82.0
180 60.0
181 65.0
182 65.0
183 58.0
184 55.0
185 45.0
186 60.0
187 75.0
188 43.0
189 55.0
190 26.0
191 46.0
192 61.0
193 100.0
194 44.0
195 40.0
196 45.0
197 60.0
198 58.0
199 50.0
200 55.0
201 75.0
202 48.0
203 58.0
204 35.0
205 50.0
206 55.0
207 45.0
208 36.0
209 60.0
210 89.0
211 45.0
212 58.0
213 30.0
214 65.0
215 60.0
216 50.0
217 55.0
218 55.0
219 75.0
220 65.0
221 45.0
222 54.0
223 15.0
224 32.0
225 38.0
226 73.0
227 50.0
228 57.0
229 69.0
230 62.0
231 78.0
232 42.0
233 46.0
234 67.0
235 69.0
236 55.0
237 55.0
238 48.0
239 65.0
240 60.0
241 75.0
242 57.0
243 49.0
244 57.0
245 53.0
246 45.0
247 94.0
248 55.0
249 65.0
250 56.0
251 63.0
252 65.0
253 85.0
254 52.0
255 80.0
256 45.0
257 68.0
258 53.0
259 50.0
260 72.0
261 65.0
262 49.0
263 43.0
264 42.0
265 53.0
266 47.0
267 58.0
268 65.0
269 45.0
270 61.0
271 63.0
272 60.0
273 58.0
274 50.0
275 60.0
276 65.0
277 42.0
278 30.0
279 50.0
280 60.0
281 62.0
282 56.0
283 65.0
284 55.0
285 63.0
286 60.0
287 40.0
288 56.0
289 78.0
290 55.0
291 75.0
292 50.0
293 65.0
294 58.0
295 60.0
296 65.0
297 70.0
298 57.0
299 65.0
300 70.0
301 50.0
302 86.0
303 47.0
304 55.0
305 75.0
306 30.0
307 80.0
308 60.0
309 55.0
310 45.0
311 65.0
312 60.0
313 45.0
314 75.0
315 75.0
316 45.0
317 48.0
318 69.0
319 60.0
320 50.0
321 65.0
322 75.0
323 70.0
324 50.0
325 72.0
326 44.0
327 55.0
328 60.0
329 67.0
330 55.0
331 70.0
332 62.0
333 46.0
334 35.0
335 65.0
336 62.0
337 64.0
338 35.0
339 45.0
340 48.0
341 76.0
342 35.0
343 48.0
344 52.0
345 82.0
346 67.0
347 57.0
348 61.0
349 41.0
350 43.0
351 60.0
352 45.0
353 59.0
354 55.0
355 67.0
356 67.0
357 43.0
358 69.0
359 70.0
360 50.0
361 84.0
362 72.0
363 56.0
364 68.0
365 55.0
366 60.0
367 69.0
368 55.0
369 24.0
370 57.0
371 55.0
372 56.0
373 54.0
374 90.0
375 40.0
376 75.0
377 75.0
378 55.0
379 55.0
380 38.0
381 58.0
382 52.0
383 56.0
384 45.0
385 51.0
386 54.0
387 45.0
388 60.0
389 49.0
390 62.0
391 50.0
392 65.0
393 50.0
394 28.0
395 45.0
396 69.0
397 85.0
398 55.0
399 69.0
400 64.0
401 30.0
402 56.0
403 60.0
404 89.0
405 60.0
406 55.0
407 50.0
408 58.0
409 70.0
410 61.0
411 65.0
412 40.0
413 52.0
414 72.0
415 55.0
416 70.0
417 43.0
418 42.0
419 65.0
420 52.0
421 65.0
422 50.0
423 65.0
424 54.0
425 45.0
426 50.0
427 75.0
428 58.0
429 61.0
430 50.0
431 57.0
432 55.0
433 60.0
434 70.0
435 60.0
436 55.0
437 nan
438 59.0
439 65.0
440 40.0
441 50.0
442 75.0
443 56.0
444 57.0
445 55.0
446 60.0
447 32.0
448 55.0
449 59.0
450 50.0
451 75.0
452 90.0
453 56.0
454 35.0
455 33.0
456 45.0
457 65.0
458 57.0
459 60.0
460 59.0
461 45.0
462 70.0
463 63.0
464 55.0
465 38.0
466 37.0
467 26.0
468 50.0
469 61.0
470 52.0
471 70.0
472 46.0
473 70.0
474 62.0
475 53.0
476 50.0
477 68.0
478 70.0
479 60.0
480 52.0
481 84.0
482 53.0
483 64.0
484 62.0
485 48.0
486 63.0
487 44.0
488 51.0
489 59.0
490 55.0
491 50.0
492 60.0
493 46.0
494 60.0
495 35.0
496 60.0
497 37.0
498 65.0
499 36.0
500 44.0
501 60.0
502 75.0
503 55.0
504 50.0
505 67.0
506 58.0
507 45.0
508 42.0
509 46.0
510 47.0
511 27.0
512 51.0
513 40.0
514 65.0
515 56.0
516 43.0
517 45.0
518 40.0
519 40.0
520 44.0
521 40.0
522 56.0
523 47.0
524 49.0
525 50.0
526 51.0
527 39.0
528 48.0
529 53.0
530 48.0
531 40.0
532 53.0
533 46.0
534 46.0
535 55.0
536 53.0
537 44.0
538 40.0
539 42.0
540 50.0
541 50.0
542 51.0
543 52.0
544 50.0
545 48.0
546 40.0
547 55.0
548 53.0
549 40.0
550 51.0
551 29.0
552 43.0
553 42.0
554 35.0
555 nan
556 46.0
557 42.0
558 45.0
559 45.0
560 48.0
561 53.0
562 42.0
563 30.0
564 25.0
565 30.0
566 50.0
567 42.0
568 26.0
569 48.0
570 41.0
571 45.0
572 28.0
573 27.0
574 42.0
575 32.0
576 39.0
577 66.0
578 35.0
579 55.0
580 37.0
581 45.0
582 64.0
583 60.0
584 47.0
585 58.0
586 32.0
587 nan
588 36.0
589 49.0
590 46.0
591 33.0
592 43.0
593 40.0
594 34.0
595 49.0
596 46.0
597 47.0
598 33.0
599 21.0
600 36.0
601 58.0
602 59.0
603 47.0
604 45.0
605 45.0
606 50.0
607 47.0
608 42.0
609 48.0
610 55.0
611 60.0
612 28.0
613 49.0
614 44.0
615 38.0
616 35.0
617 25.0
618 42.0
619 48.0
620 60.0
621 54.0
622 70.0
623 33.0
624 45.0
625 45.0
626 46.0
627 52.0
628 42.0
629 48.0
630 40.0
631 38.0
632 52.0
633 50.0
634 45.0
635 45.0
636 44.0
637 50.0
638 48.0
639 40.0
640 52.0
641 40.0
642 34.0
643 46.0
644 46.0
645 47.0
646 44.0
647 26.0
648 41.0
649 42.0
650 44.0
651 40.0
652 40.0
653 42.0
654 47.0
655 41.0
656 37.0
657 46.0
658 54.0
659 40.0
660 50.0
661 50.0
662 40.0
663 42.0
664 42.0
665 48.0
666 45.0
667 30.0
668 48.0
669 45.0
670 41.0
671 40.0
672 27.0
673 48.0
674 47.0
675 70.0
676 48.0
677 30.0
678 46.0
679 60.0
680 40.0
681 50.0
682 40.0
683 29.0
684 32.0
685 26.0
686 45.0
687 35.0
688 38.0
689 35.0
690 32.0
691 25.0
692 40.0
693 42.0
694 30.0
695 33.0
696 30.0
697 45.0
698 40.0
699 30.0
700 38.0
701 32.0
702 30.0
703 28.0
704 38.0
705 38.0
706 31.0
707 72.0
708 71.0
709 65.0
710 80.0
711 45.0
712 85.0
713 60.0
714 65.0
715 52.0
716 70.0
717 26.0
718 62.0
719 61.0
720 77.0
721 35.0
722 48.0
723 53.0
724 35.0
725 64.0
726 26.0
727 48.0
728 40.0
729 52.0
730 45.0
731 30.0
732 65.0
733 50.0
734 62.0
735 40.0
736 65.0
737 52.0
738 45.0
739 60.0
740 60.0
741 70.0
742 54.0
743 60.0
744 80.0
745 52.0
746 42.0
747 55.0
748 60.0
749 38.0
750 50.0
751 65.0
752 65.0
753 80.0
754 49.0
755 67.0
756 37.0
757 70.0
758 80.0
759 75.0
760 47.0
761 28.0
762 72.0
763 60.0
764 66.0
765 62.0
766 56.0
767 55.0
768 55.0
769 55.0
770 36.0
771 48.0
772 55.0
773 66.0
774 57.0
775 50.0
776 50.0
777 57.0
778 35.0
779 64.0
780 47.0
781 50.0
782 52.0
783 48.0
784 27.0
785 60.0
786 45.0
787 57.0
788 55.0
789 60.0
790 62.0
791 48.0
792 50.0
793 55.0
794 70.0
795 60.0
796 65.0
797 44.0
798 42.0
799 56.0
800 67.0
801 28.0
802 64.0
803 43.0
804 62.0
805 50.0
806 70.0
807 62.0
808 29.0
809 31.0
810 55.0
811 46.0
812 31.0
813 46.0
814 38.0
815 42.0
816 39.0
817 58.0
818 33.0
819 56.0
820 57.0
821 46.0
822 35.0
823 72.0
824 39.0
825 59.0
826 40.0
827 83.0
828 45.0
829 45.0
830 50.0
831 45.0
832 56.0
833 46.0
834 45.0

In [14]:
type(df.Age[94])

numpy.float64

In [15]:
df.rename(columns = {'IHD-HeartAttack':'output'},inplace=True)

In [16]:
df.columns

Index(['Age', 'Sex', 'Smoking', 'HTN', 'DLP', 'DM', 'Physical Exercise',
       'Family History', 'Drug History', 'Psychological Stress', 'Chest Pain',
       'Dyspnea', 'Palpitation', 'ECG', 'output'],
      dtype='object')

In [17]:
df_with_0 = df.fillna(-20)

In [18]:
df_with_0.isnull().sum()

Age                     0
Sex                     0
Smoking                 0
HTN                     0
DLP                     0
DM                      0
Physical Exercise       0
Family History          0
Drug History            0
Psychological Stress    0
Chest Pain              0
Dyspnea                 0
Palpitation             0
ECG                     0
output                  0
dtype: int64

In [19]:
for i in range(df.Age.shape[0]):
    print(i,df_with_0.Age[i])

0 65.0
1 48.0
2 80.0
3 67.0
4 55.0
5 85.0
6 80.0
7 75.0
8 26.0
9 69.0
10 65.0
11 50.0
12 63.0
13 62.0
14 63.0
15 65.0
16 55.0
17 45.0
18 60.0
19 70.0
20 54.0
21 50.0
22 26.0
23 91.0
24 80.0
25 47.0
26 50.0
27 42.0
28 75.0
29 60.0
30 68.0
31 53.0
32 55.0
33 70.0
34 34.0
35 50.0
36 55.0
37 70.0
38 85.0
39 45.0
40 70.0
41 65.0
42 50.0
43 42.0
44 61.0
45 70.0
46 47.0
47 55.0
48 50.0
49 50.0
50 55.0
51 85.0
52 41.0
53 65.0
54 67.0
55 70.0
56 68.0
57 68.0
58 42.0
59 30.0
60 75.0
61 49.0
62 50.0
63 60.0
64 50.0
65 40.0
66 30.0
67 43.0
68 64.0
69 45.0
70 64.0
71 45.0
72 30.0
73 57.0
74 90.0
75 36.0
76 45.0
77 60.0
78 75.0
79 62.0
80 62.0
81 65.0
82 76.0
83 40.0
84 53.0
85 59.0
86 44.0
87 50.0
88 63.0
89 49.0
90 48.0
91 40.0
92 60.0
93 45.0
94 -20.0
95 88.0
96 65.0
97 67.0
98 55.0
99 50.0
100 54.0
101 52.0
102 60.0
103 50.0
104 65.0
105 55.0
106 58.0
107 60.0
108 60.0
109 45.0
110 50.0
111 94.0
112 45.0
113 54.0
114 40.0
115 58.0
116 69.0
117 75.0
118 52.0
119 65.0
120 89.0
121 47.0
122 55.0
123 60.0
124 40.0
125 36.0
126 75.0
127 55.0
128 60.0
129 59.0
130 63.0
131 55.0
132 65.0
133 54.0
134 52.0
135 60.0
136 75.0
137 55.0
138 55.0
139 59.0
140 55.0
141 40.0
142 45.0
143 67.0
144 57.0
145 75.0
146 42.0
147 66.0
148 56.0
149 56.0
150 63.0
151 60.0
152 38.0
153 84.0
154 65.0
155 55.0
156 65.0
157 35.0
158 67.0
159 55.0
160 57.0
161 58.0
162 85.0
163 60.0
164 30.0
165 35.0
166 69.0
167 87.0
168 65.0
169 50.0
170 53.0
171 65.0
172 43.0
173 48.0
174 58.0
175 30.0
176 52.0
177 55.0
178 65.0
179 82.0
180 60.0
181 65.0
182 65.0
183 58.0
184 55.0
185 45.0
186 60.0
187 75.0
188 43.0
189 55.0
190 26.0
191 46.0
192 61.0
193 100.0
194 44.0
195 40.0
196 45.0
197 60.0
198 58.0
199 50.0
200 55.0
201 75.0
202 48.0
203 58.0
204 35.0
205 50.0
206 55.0
207 45.0
208 36.0
209 60.0
210 89.0
211 45.0
212 58.0
213 30.0
214 65.0
215 60.0
216 50.0
217 55.0
218 55.0
219 75.0
220 65.0
221 45.0
222 54.0
223 15.0
224 32.0
225 38.0
226 73.0
227 50.0
228 57.0
229 69.0
230 62.0
231 78.0
232 42.0
233 46.0
234 67.0
235 69.0
236 55.0
237 55.0
238 48.0
239 65.0
240 60.0
241 75.0
242 57.0
243 49.0
244 57.0
245 53.0
246 45.0
247 94.0
248 55.0
249 65.0
250 56.0
251 63.0
252 65.0
253 85.0
254 52.0
255 80.0
256 45.0
257 68.0
258 53.0
259 50.0
260 72.0
261 65.0
262 49.0
263 43.0
264 42.0
265 53.0
266 47.0
267 58.0
268 65.0
269 45.0
270 61.0
271 63.0
272 60.0
273 58.0
274 50.0
275 60.0
276 65.0
277 42.0
278 30.0
279 50.0
280 60.0
281 62.0
282 56.0
283 65.0
284 55.0
285 63.0
286 60.0
287 40.0
288 56.0
289 78.0
290 55.0
291 75.0
292 50.0
293 65.0
294 58.0
295 60.0
296 65.0
297 70.0
298 57.0
299 65.0
300 70.0
301 50.0
302 86.0
303 47.0
304 55.0
305 75.0
306 30.0
307 80.0
308 60.0
309 55.0
310 45.0
311 65.0
312 60.0
313 45.0
314 75.0
315 75.0
316 45.0
317 48.0
318 69.0
319 60.0
320 50.0
321 65.0
322 75.0
323 70.0
324 50.0
325 72.0
326 44.0
327 55.0
328 60.0
329 67.0
330 55.0
331 70.0
332 62.0
333 46.0
334 35.0
335 65.0
336 62.0
337 64.0
338 35.0
339 45.0
340 48.0
341 76.0
342 35.0
343 48.0
344 52.0
345 82.0
346 67.0
347 57.0
348 61.0
349 41.0
350 43.0
351 60.0
352 45.0
353 59.0
354 55.0
355 67.0
356 67.0
357 43.0
358 69.0
359 70.0
360 50.0
361 84.0
362 72.0
363 56.0
364 68.0
365 55.0
366 60.0
367 69.0
368 55.0
369 24.0
370 57.0
371 55.0
372 56.0
373 54.0
374 90.0
375 40.0
376 75.0
377 75.0
378 55.0
379 55.0
380 38.0
381 58.0
382 52.0
383 56.0
384 45.0
385 51.0
386 54.0
387 45.0
388 60.0
389 49.0
390 62.0
391 50.0
392 65.0
393 50.0
394 28.0
395 45.0
396 69.0
397 85.0
398 55.0
399 69.0
400 64.0
401 30.0
402 56.0
403 60.0
404 89.0
405 60.0
406 55.0
407 50.0
408 58.0
409 70.0
410 61.0
411 65.0
412 40.0
413 52.0
414 72.0
415 55.0
416 70.0
417 43.0
418 42.0
419 65.0
420 52.0
421 65.0
422 50.0
423 65.0
424 54.0
425 45.0
426 50.0
427 75.0
428 58.0
429 61.0
430 50.0
431 57.0
432 55.0
433 60.0
434 70.0
435 60.0
436 55.0
437 -20.0
438 59.0
439 65.0
440 40.0
441 50.0
442 75.0
443 56.0
444 57.0
445 55.0
446 60.0
447 32.0
448 55.0
449 59.0
450 50.0
451 75.0
452 90.0
453 56.0
454 35.0
455 33.0
456 45.0
457 65.0
458 57.0
459 60.0
460 59.0
461 45.0
462 70.0
463 63.0
464 55.0
465 38.0
466 37.0
467 26.0
468 50.0
469 61.0
470 52.0
471 70.0
472 46.0
473 70.0
474 62.0
475 53.0
476 50.0
477 68.0
478 70.0
479 60.0
480 52.0
481 84.0
482 53.0
483 64.0
484 62.0
485 48.0
486 63.0
487 44.0
488 51.0
489 59.0
490 55.0
491 50.0
492 60.0
493 46.0
494 60.0
495 35.0
496 60.0
497 37.0
498 65.0
499 36.0
500 44.0
501 60.0
502 75.0
503 55.0
504 50.0
505 67.0
506 58.0
507 45.0
508 42.0
509 46.0
510 47.0
511 27.0
512 51.0
513 40.0
514 65.0
515 56.0
516 43.0
517 45.0
518 40.0
519 40.0
520 44.0
521 40.0
522 56.0
523 47.0
524 49.0
525 50.0
526 51.0
527 39.0
528 48.0
529 53.0
530 48.0
531 40.0
532 53.0
533 46.0
534 46.0
535 55.0
536 53.0
537 44.0
538 40.0
539 42.0
540 50.0
541 50.0
542 51.0
543 52.0
544 50.0
545 48.0
546 40.0
547 55.0
548 53.0
549 40.0
550 51.0
551 29.0
552 43.0
553 42.0
554 35.0
555 -20.0
556 46.0
557 42.0
558 45.0
559 45.0
560 48.0
561 53.0
562 42.0
563 30.0
564 25.0
565 30.0
566 50.0
567 42.0
568 26.0
569 48.0
570 41.0
571 45.0
572 28.0
573 27.0
574 42.0
575 32.0
576 39.0
577 66.0
578 35.0
579 55.0
580 37.0
581 45.0
582 64.0
583 60.0
584 47.0
585 58.0
586 32.0
587 -20.0
588 36.0
589 49.0
590 46.0
591 33.0
592 43.0
593 40.0
594 34.0
595 49.0
596 46.0
597 47.0
598 33.0
599 21.0
600 36.0
601 58.0
602 59.0
603 47.0
604 45.0
605 45.0
606 50.0
607 47.0
608 42.0
609 48.0
610 55.0
611 60.0
612 28.0
613 49.0
614 44.0
615 38.0
616 35.0
617 25.0
618 42.0
619 48.0
620 60.0
621 54.0
622 70.0
623 33.0
624 45.0
625 45.0
626 46.0
627 52.0
628 42.0
629 48.0
630 40.0
631 38.0
632 52.0
633 50.0
634 45.0
635 45.0
636 44.0
637 50.0
638 48.0
639 40.0
640 52.0
641 40.0
642 34.0
643 46.0
644 46.0
645 47.0
646 44.0
647 26.0
648 41.0
649 42.0
650 44.0
651 40.0
652 40.0
653 42.0
654 47.0
655 41.0
656 37.0
657 46.0
658 54.0
659 40.0
660 50.0
661 50.0
662 40.0
663 42.0
664 42.0
665 48.0
666 45.0
667 30.0
668 48.0
669 45.0
670 41.0
671 40.0
672 27.0
673 48.0
674 47.0
675 70.0
676 48.0
677 30.0
678 46.0
679 60.0
680 40.0
681 50.0
682 40.0
683 29.0
684 32.0
685 26.0
686 45.0
687 35.0
688 38.0
689 35.0
690 32.0
691 25.0
692 40.0
693 42.0
694 30.0
695 33.0
696 30.0
697 45.0
698 40.0
699 30.0
700 38.0
701 32.0
702 30.0
703 28.0
704 38.0
705 38.0
706 31.0
707 72.0
708 71.0
709 65.0
710 80.0
711 45.0
712 85.0
713 60.0
714 65.0
715 52.0
716 70.0
717 26.0
718 62.0
719 61.0
720 77.0
721 35.0
722 48.0
723 53.0
724 35.0
725 64.0
726 26.0
727 48.0
728 40.0
729 52.0
730 45.0
731 30.0
732 65.0
733 50.0
734 62.0
735 40.0
736 65.0
737 52.0
738 45.0
739 60.0
740 60.0
741 70.0
742 54.0
743 60.0
744 80.0
745 52.0
746 42.0
747 55.0
748 60.0
749 38.0
750 50.0
751 65.0
752 65.0
753 80.0
754 49.0
755 67.0
756 37.0
757 70.0
758 80.0
759 75.0
760 47.0
761 28.0
762 72.0
763 60.0
764 66.0
765 62.0
766 56.0
767 55.0
768 55.0
769 55.0
770 36.0
771 48.0
772 55.0
773 66.0
774 57.0
775 50.0
776 50.0
777 57.0
778 35.0
779 64.0
780 47.0
781 50.0
782 52.0
783 48.0
784 27.0
785 60.0
786 45.0
787 57.0
788 55.0
789 60.0
790 62.0
791 48.0
792 50.0
793 55.0
794 70.0
795 60.0
796 65.0
797 44.0
798 42.0
799 56.0
800 67.0
801 28.0
802 64.0
803 43.0
804 62.0
805 50.0
806 70.0
807 62.0
808 29.0
809 31.0
810 55.0
811 46.0
812 31.0
813 46.0
814 38.0
815 42.0
816 39.0
817 58.0
818 33.0
819 56.0
820 57.0
821 46.0
822 35.0
823 72.0
824 39.0
825 59.0
826 40.0
827 83.0
828 45.0
829 45.0
830 50.0
831 45.0
832 56.0
833 46.0
834 45.0

In [20]:
df_with_0['Drug History'][14]

-20

In [20]:
df.Smoking.value_counts(dropna=False)

no     502
yes    245
ex      85
NaN      3
Name: Smoking, dtype: int64

In [21]:
df_new = df.dropna(how='any/all',thresh=2)

In [22]:
df[df.Smoking.isnull()]

,Age,Sex,Smoking,HTN,DLP,DM,Physical Exercise,Family History,Drug History,Psychological Stress,Chest Pain,Dyspnea,Palpitation,ECG,output
120,89.0,Male,NaN,yes,yes,yes,no,yes,yes,no,no,yes,no,abnormal,Yes
201,75.0,Female,NaN,yes,yes,yes,no,yes,yes,no,yes,no,no,abnormal,Yes
241,75.0,Male,NaN,yes,no,no,no,NaN,yes,no,no,no,no,abnormal,Yes

In [24]:
df_with_0.drop("DM",axis=1,inplace=True)

In [25]:
df_with_0.head()

,Age,Sex,Smoking,HTN,DLP,Physical Exercise,Family History,Drug History,Psychological Stress,Chest Pain,Dyspnea,Palpitation,ECG,output
0,65.0,Male,no,yes,no,no,no,yes,no,yes,no,no,abnormal,Yes
1,48.0,Male,no,yes,no,no,no,yes,no,yes,no,no,abnormal,No
2,80.0,Male,ex,yes,no,yes,no,yes,no,no,no,no,abnormal,Yes
3,67.0,Male,yes,yes,no,no,no,yes,no,yes,yes,no,abnormal,Yes
4,55.0,Male,yes,yes,no,no,no,no,no,yes,yes,no,abnormal,Yes

In [23]:
df_with_0.shape

(835, 15)

In [27]:
df_with_0.dropna(subset=['ECG']).shape

(835, 14)

In [24]:
df.isnull().sum()

Age                      4
Sex                      1
Smoking                  3
HTN                      3
DLP                      8
DM                       1
Physical Exercise        9
Family History           7
Drug History            28
Psychological Stress    15
Chest Pain               3
Dyspnea                  2
Palpitation              5
ECG                     36
output                   0
dtype: int64

In [29]:
df.dropna(subset=['ECG']).shape

(799, 15)

In [30]:
d = df.dropna(subset=['ECG'])

In [31]:
d.head()

,Age,Sex,Smoking,HTN,DLP,DM,Physical Exercise,Family History,Drug History,Psychological Stress,Chest Pain,Dyspnea,Palpitation,ECG,output
0,65.0,Male,no,yes,no,yes,no,no,yes,no,yes,no,no,abnormal,Yes
1,48.0,Male,no,yes,no,yes,no,no,yes,no,yes,no,no,abnormal,No
2,80.0,Male,ex,yes,no,yes,yes,no,yes,no,no,no,no,abnormal,Yes
3,67.0,Male,yes,yes,no,no,no,no,yes,no,yes,yes,no,abnormal,Yes
4,55.0,Male,yes,yes,no,no,no,no,no,no,yes,yes,no,abnormal,Yes

In [32]:
x=df.values

In [25]:
for i in range(len(df)):
    print(x[i])

NameError: name 'x' is not defined